---

management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  profiles: projects
  application:
    name: projects

server:
  port: 8081

projects:
  standalone: true
allocations:
  standalone: false

---
spring:
  profiles: allocations
  application:
    name: allocations

server:
  port: 8082

projects:
  standalone: false
allocations:
  standalone: true

---
spring:
  profiles: monolith
  application:
    name: monolith

server:
  port: 8080

projects:
  standalone: false
allocations:
  standalone: false
