management.endpoints.web.exposure.include: "*"
spring.config.use-legacy-processing: true
# at some point read https://medium.com/@iamdeepinjava/rewriting-application-properties-in-sprignboot-2-4-style-a32f4604656c
---
spring.profiles: projects
spring.application.name: projects
server.port: 8081
---
spring.profiles: allocations
spring.application.name: allocations
server.port: 8082
---
spring.profiles: monolith-settings
spring.application.name: monolith
server.port: 8080
---
spring.profiles: monolith
spring.profiles.include: projects, allocations, monolith-settings
