spring:
  application:
    name: monolith

server:
  port: 8080

services:
  active:
    - projects
    - allocations

management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  profiles: projects
  application:
    name: projects

server:
  port: 8081

services:
  active:
    - projects

---
spring:
  profiles: allocations
  application:
    name: allocations

server:
  port: 8082

services:
  active:
    - allocations
